Update saclettre.c
paulakaferreira/scrabble pull request #10
Opened 2022-12-29 09:05 UTC by lucaslrx

update : 
- small fixes on the array of structures
- the function sac_lettres initialize an array of letters (tabjeton) standing for our bag of letters, using the quantity attribute from the array of structure tablettre
- the function affichage_sac is displaying the tabjeton array

2022-12-31 20:40 UTC, paulakaferreira requested changes

2022-12-31 20:40 UTC, paulakaferreira commented on saclettre.c
> +char tabjeton[TOTAL_JETON - 1];
Shouldn't it be 'MAX_LETTRE' instead of 'MAX_LETTRE - 1' ? :)
Same for TOTAL_JETON

2023-01-13 13:47 UTC, lucaslrx commented on saclettre.c
> +char tabjeton[TOTAL_JETON - 1];
agreed !

2023-01-15 09:37 UTC, paulakaferreira approved these changes

2023-01-15 09:37 UTC, merged