Create init_player.c
paulakaferreira/scrabble pull request #11
Opened 2022-12-29 09:16 UTC by lucaslrx

2022-12-31 20:44 UTC, paulakaferreira requested changes

2022-12-31 20:44 UTC, paulakaferreira commented on init_player.c
> +  char jeton[MAX_JETON_TOUR - 1];
Shouldn't it be jeton[MAX_JETON_TOUR]?

2023-01-04 12:52 UTC, lucaslrx commented on init_player.c
> +  char jeton[MAX_JETON_TOUR - 1];
agreed!

2023-01-15 09:35 UTC, paulakaferreira approved these changes
OK

2023-01-15 09:36 UTC, merged